### ISSUE TITLE
specs for the motor?

### ISSUE THREAD

**Issue by mhered** [Ezward/diyduckie#1]
@Ezward congrats on this great initiative. I would be happy to contribute. At this stage I am not yet very proficient in electronics or robotics but I could offer trying to build the bot following your instructions as a way of proof reading your guide. 

Asking 'silly' questions along the way could perhaps help make the guide more foolproof / accesible.

For example: I was looking at buying the components and I got stuck because I don't know which RPMs I should choose for the motors.

Let me know what you think and if you want maybe lets get in touch through other means to discuss further

**Comment by Ezward** [comment]
@mhered Thanks for contacting; I apologize the long delay.  If you are still interested, the motor I used is the 41RPM motor; it is the slowest, but it provides the highest resolution encoder output as a result.  51RPM or 75RPM would probably work well also, they would just have a slightly different number of encoder ticks per revolution.

**Comment by Ezward** [comment]
I added and RPM recommendation to the README.md.  Thanks for pointing that out.

**Comment by mhered** [comment]
Thanks! I am planning on building the diy Duckiebot after the holiday break, around September. As mentioned I can offer to contribute to the project documentation if you are interested.
